### ISSUE TITLE
Bet confirmation is not obvious

### ISSUE THREAD

**Issue by thedomino1313** [AI-and-Blockchain/F23_Blackjack_AI#48]
It is unclear how the betting mechanism works. There is a plus, minus, and "bet" button. It is not clear that the bet button locks in the value determined by the plus and minus.

One solution is to change the bet button to read "submit"

(Documentation in the readme does provide explanation on this mechanism, however it should be intuitive and not require documentation)

**Comment by thedomino1313** [comment]
The completion of the bet placing is now obvious. I think a good thing to add would be greying out buttons that cannot be used.

**Comment by thedomino1313** [comment]
> The completion of the bet placing is now obvious. I think a good thing to add would be greying out buttons that cannot be used.

#65 addresses this further

**Comment by alstar555** [comment]
Graying out button complete
